<?
$blog_info = [
    'name' => 'もちツールズ',
    'description' => '',
    'home' => 'tools.motisan.info',//top
    'base' => '//tools.motisan.info/',//base url
    'top-nav-txt' => 'もちもち便利ツール',
    'header-img'=>'./i/header.png.webp',
    'author'=>'もちさん',
    'twitter'=>'@motimoti_dev',
    'theme-color'=>'#FFEAD8',
    'og:image'=>'./i/ogp.png',
    'top-h2'=>'うおおおおおおおおおおおお！',
    'privacy-policy'=>'./privacy-policy/'
];
if(isset($_GET['local'])){
    $blog_info['home'] = 'localhost/github/tools2';
}
$example = [
    [
        'title'=>'テストツール',
        'url'=>'./tools/example/',
        'user'=>'',
        'description'=>'テストのツールです',
        'img'=>'i/example.png',
        'date'=>'2023/05/07',
        'var'=>'1.0',
        'id'=>'example',
        'view'=>true
    ]
];
$tools = [
    [
        'title'=>'テキストファイル内容確認ツール',
        'url'=>'./tools/show-text/',
        'user'=>'',
        'description'=>'Web上でファイル内の文字列を確認するツールです！',
        'img'=>'i/show-text.png',
        'date'=>'2023/04/14',
        'var'=>'1.0',
        'id'=>'show-text',
        'view'=>true
    ],
    [
        'title'=>'文字置換ツール',
        'url'=>'./tools/text-replace/',
        'user'=>'',
        'description'=>'指定した文字を一括で置き換えるツールです！',
        'img'=>'i/text-replace.png',
        'date'=>'2023/04/14',
        'var'=>'1.0',
        'id'=>'text-replace',
        'view'=>true
    ],
    [
        'title'=>'予定入りカレンダー生成',
        'url'=>'./tools/calendar-generator/output.php',
        'user'=>'',
        'description'=>'文字やアイコンの入ったカレンダーを生成できます！',
        'img'=>'i/calendar-generator.png',
        'date'=>'2023/04/30',
        'var'=>'1.0',
        'id'=>'calendar-generator',
        'view'=>true
    ],
    [
        'title'=>'もちイラスト博物館',
        'url'=>'./tools/src-illust/',
        'user'=>'',
        'description'=>'イラストが検索できます！',
        'img'=>'i/src-illust.png',
        'date'=>'2023/05/6',
        'var'=>'1.0',
        'id'=>'src-illust',
        'view'=>true
    ],
    [
        'title'=>'メタタグジェネレーター',
        'url'=>'./tools/meta-tag-generator/',
        'user'=>'',
        'description'=>'HTMLのメタタグを作成できます',
        'img'=>'i/meta-tag-generator.png',
        'date'=>'2023/06/9',
        'var'=>'1.0',
        'id'=>'meta-tag-generator',
        'view'=>true
    ],
    [
        'title'=>'もち的コピペ集',
        'url'=>'./tools/copy-paste/',
        'user'=>'',
        'description'=>'もちが個人的によく使う文字列をコピペできます',
        'img'=>'i/copy-paste.png',
        'date'=>'2023/06/9',
        'var'=>'1.0',
        'id'=>'copy-paste',
        'view'=>true
    ],
    /*[
        'title'=>'',
        'url'=>'',
        'user'=>'',
        'description'=>'',
        'img'=>'',//base urlに続くurlを指定
        'date'=>'',
        'var'=>'',
    ]*/
];
?>